################################################################################################################################
# Entorno para desarrollo
################################################################################################################################
spring:
 profiles: DES
 datasource:
  sqlScriptEncoding: UTF-8
 
config:
 eureka:
  endpoint:
   gateway: GATEWAY
   backautenticacion: SR-BACK-AUTENTICACION
   backadministracion: SR-BACK-ADMINISTRACION
   backconfiguracion: SR-BACK-CONFIGURACION
 endpoint:
  backautenticacion: http://172.18.3.124:8001
 server:
  context-paths:
   sr-gateway: /gateway
   sr-eureka: /eureka
   sr-back-configuracion: /back-configuracion
   sr-back-autenticacion: /back-autenticacion
   sr-back-administracion: /back-administracion
  
server:
 error:
  include-stacktrace: never
  
eureka:
 instance:
  initialStatus: UNKNOWN
 client:
  healthcheck:
   enabled: true
