################################################################################################################################
# Entorno de desarrollo
################################################################################################################################

# Puerto por defecto de Eureka
server:
  port: 8761
  servlet:
   context-path: ${config.server.context-paths.sto-eureka}
  
# Credenciales de seguridad 
spring:
 profiles: DES
 security:
   user:
     name: adminEureka
     password: '{cipher}954cc28655bd7efcb495ce77ea22d4f3c8b6e933565337ce41b3916a2135fc39'

# Configuración de Eureka  
eureka:
  instance:
#    hostname: localhost
    preferIpAddress: true
  client:
    register-with-eureka: false
    fetch-registry: false
      
# Configuración de logging        
logging:
  file: /usr/local/nuevaarquitecturasto/logs/eureka.log
  level:
    org:
      springframework:
        security: ERROR
    com:
      netflix:
        eureka: OFF
        discovery: OFF
